alias gpush='git push'
alias gpull='git pull'
alias gstatus='git status'
alias gdeploy='git add . && echo -n "Deploy message: " && read msg && git commit -m "" && git push'
alias gmu='git add . && git commit -m "update" && git push'
